### ISSUE TITLE
loop issue

### ISSUE THREAD

**Issue by Foresterrr** [Foresterrr/search#1]
languages = 0
item = 0

def binary_search(item, languages):
  
    languages = ["Ada", "C", "C++", "Cobol", "Eifel", "Erlang", "Fortran", "Go", "Java", "Lisp", "Pascal", "Perl", "Python", "Ruby", "Smalltalk"]
    searchLang = input("Enter a language to search for: ")
    smallest = 0
    largest = len(languages) - 1
    item = languages.index(searchLang)
    print(item)
    

    midpoint = len(languages)//2

    while (languages[midpoint] != item):
        print("Midpoint is not; ", searchLang)
        if item == languages(midpoint):
            return True
        elif item < languages(midpoint):
            largest = midpoint - 1
        else:
            low = mid + 1
        return False

print[binary_search(item, languages)]

**Comment by Foresterrr** [comment]
languages = ["Ada", "C", "C++", "Cobol", "Eifel", "Erlang", "Fortran", "Go", "Java", "Lisp", "Pascal", "Perl", "Python", "Ruby", "Smalltalk"]

    searchLang = input("Enter a language to search for: ")

    midpoint = len(languages)//2

    while (languages[midpoint] != searchLang):
        return ("Foobar")

**Comment by Foresterrr** [comment]
The smaller set of code is what I was provided with and here is the prompt:  

Finish the binary search algorithm in the attached Python or Java file.  You can change the loop structure if you wish if you're thinking of a different way to solve the problem.  At this point, you can assume that the search Language WILL BE in the list.   Print the array/list index where the language was found.

**Comment by tr0yspradling** [comment]
```
def binary_search(item, itemList):
    first, last, middle = 0, len(itemList) - 1, 0
    found = False
    while first <= last and not found:
        middle = (first + last) // 2
        if itemList[middle] == item:
            found = True
        else:
            if item < itemList[middle]:
                last = middle - 1
            else:
                first = middle + 1
    return (found, middle)

languages = ["Ada", "C", "C++", "Cobol", "Eifel", "Erlang", "Fortran", "Go", "Java", "Lisp", "Pascal", "Perl", "Python", "Ruby", "Smalltalk"]
choice = input("Enter a language to search for: ")

found, position = binary_search(choice, languages)
print('Found %s @ position %s.' % (choice, position)) if found else print('Not found!')

```

**Comment by tr0yspradling** [comment]
```
def binary_search(item, itemList):
    first, last, middle = 0, len(itemList) - 1, 0
    found = False
    while first <= last and not found:
        middle = (first + last) // 2
        if itemList[middle] == item:
            found = True
        else:
            if item < itemList[middle]:
                last = middle - 1
            else:
                first = middle + 1
    return (found, middle) if found else (found, None)

languages = ["Ada", "C", "C++", "Cobol", "Eifel", "Erlang", "Fortran", "Go", "Java", "Lisp", "Pascal", "Perl", "Python", "Ruby", "Smalltalk"]
choice = input("Enter a language to search for: ")

found, position = binary_search(choice, languages)
print('Found %s @ %s.' % (choice, position)) if found else print('Not found!')

```
